version: '3'
services:
  ftp:
    image: fauria/vsftpd
    container_name: vsftpd_jaula
    platform: linux/amd64
    volumes:
      - ./ftp_data:/home/vsftpd 
      - ./vsftpd.conf:/etc/vsftpd/vsftpd.conf 
    ports:
      - "21:21" 
      - "21100-21110:21100-21110" 
    environment:
      FTP_USER: myuser
      FTP_PASS: mypass
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110